### ISSUE TITLE
Line 505 Contains invalid character "/" affecting Plex running on Linux

### ISSUE THREAD

**Issue by wcarlson40** [mrsilver76/itunes_playlist_exporter#12] opened 2022-10-29 01:06 UTC

**Comment by wcarlson40** [comment] 2022-10-29 01:08
Proposed fix:

Dim sLinux_Path
	If USE_LINUX_PATHS = True Then
		sLinux_Path = "/"
	Else
		sLinux_Path = "\"
	End If
	
	Dim sOutput : sOutput = Execute_Command("curl -sS -X POST """ & SERVER & "playlists/upload?sectionID=" & LIBRARY_ID & "&path=" & URL_Encode(sPlexPlaylistLocation & sLinux_Path & fso.GetFileName(sUploadFile)) & "&X-Plex-Token=" & TOKEN & """", False)
	If sOutput <> "" Then Call Log("Curl failed with: " & sOutput)

**Comment by mrsilver76** [comment] 2022-10-29 11:53
Thanks for raising the issue and sorry you had to go wading through the code to find the problem.

If I read your proposal correctly, the problem is that the path which is sent to the Plex API is hardcoded to use `\` when, for Linux, it should be a `/`. In which case, shouldn't the line after the `Else` state `sLinux_Path = "/"`?

Just checking I'm not misunderstanding the defect!

**Comment by wcarlson40** [comment] 2022-10-29 13:07
Sorry, I realized what I pasted into Github got mis-formatted.  I think it is clearer now and I think it is fixed above.
If you think the sLinux_Path variable should be named something more clear, that is fine too

Thanks for a great tool.  I couldn't find any other solution on the Web (even paid options) to get playlists to transfer to Plex running on my Synology NAS, so I kept at it and figured it out!

**Comment by mrsilver76** [comment] 2022-11-04 18:54
Unable to test at the moment - as any playlist I try to upload to the Plex is getting ignored.🤔 

Do you have the same issue?

**Comment by wcarlson40** [comment] 2022-11-04 19:36
No, it's working perfectly fine for me with the changes.  I assume you are running Plex on a Windows box?
Does your old (unchanged) version of the script still work?

I can install Plex to Windows and try if needed, but it's working perfectly fine on my Linux Synology NAS

**Comment by mrsilver76** [comment] 2022-11-04 19:41
The older version is broken too 😢  Plex happily accepts the request to upload the playlist (and generates no error) and the logs look like it processes the contents, but then no playlist appears. I’ve been playing around with it manually for about an hour and cannot get a playlist to upload. It’s very strange. 

Are you using Plex server 1.29.1.6316?

**Comment by wcarlson40** [comment] 2022-11-04 19:48
Weird.  It works like a champ for me.  Using Plex server 1.29.1.6316-7000

If I get bored this weekend I'll install Plex on a Windows box and see if it works for me.

**Comment by mrsilver76** [comment] 2022-11-05 11:34
I’ve tried reinstalling and it’s still broken. I’m wondering if it’s because I’m running the 32-bit version on Windows 7 (we’re using Windows Media Centre). 

How annoying.

**Comment by wcarlson40** [comment] 2022-11-05 12:34
That might be it.  In all my debugging, I read that if you are not using Windows 10 or later, that you need to download and install Curl to your machine.
I also installed (temporarily) an app called Postman to help me debug.  It doesn't seem like Plex gives you much feedback when running the script

**Comment by wcarlson40** [comment] 2022-11-05 22:39
FYI - I installed a 2nd Plex Media Server to a Windows 10 machine.  After figuring out all the configuration settings, the script works fine as well

**Comment by mrsilver76** [comment] 2022-11-06 07:57
Thank you, that’s very kind of you. So either it’s a problem with the 32-bit version or my setup. The playlists upload just fine and an API call confirms they are there - but Plex web and all clients in my house don’t display them.

**Comment by mrsilver76** [comment] 2022-12-19 18:36
Fixed in 1.7.0. Thanks for reporting this!

**Closed by mrsilver76** 2022-12-19 18:36 UTC
